### ISSUE TITLE
Помогите протестировать. Не приходит смс

### ISSUE THREAD

**Issue by msneet** [centosadmin/redmine_sms_auth#2]
Здравствуйте! Давно присматривался к Вашему плагину - очень полезная вещь. Спасибо, что выкладываете такие разработки в общий доступ!
Прочитал Вашу статью на Хабре, установил и настроил плагин согласно статье. Все встало, вроде работает, но не приходит смс. Я зарегистрировался на smsc.ru (на аккаунте есть пробные деньги), в конфигурационном файле добавил блок в раздел production. Причем при вызове указанной команды вручную из консоли - смс приходит мгновенно:
`/usr/bin/curl --silent --show-error "https://smsc.ru/sys/send.php?charset=utf-8&login=LOGIN&psw=PASSWORD&phones=%{phone}&mes=factory.southbridge.ru code: %{password}"`
А при попытке авторизоваться пишет, что смс отправлено, но ничего не приходит! Естественно, пользователю указан телефон (пробовал в разных форматах: +79ххххххххх, 79ххххххххх, 9ххххххххх); способ авторизации - через смс.

Как посмотреть логи плагина?
Как убедиться, что команда реально была вызвана?
Куда копать?

**Comment by olemskoi** [comment]
Здравствуйте!

Пожалуйста, покажите, Ваш configuration.yml (без паролей).
Ваш Redmine работает на unicorn? Если да, стоит посмотреть unicorn.stdout или unicorn.stderr в папке "redmine/log".

**Comment by msneet** [comment]
Итак,

Тестировал плагин в Bitnami Redmine 3.2.0-1 (64-bit) (VMware Virtual Machine, Ubuntu 14.04), качать отсюда: [https://bitnami.com/stack/redmine/virtual-machine](https://bitnami.com/stack/redmine/virtual-machine)
```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  redmine_sms_auth               0.0.4
```
Файл конфига (целиком, как есть): https://www.dropbox.com/s/97bz9ajgvlq1xyx/configuration.yml?dl=0

При вызове команды вручную из консоли отправляет сообщение на тестовый телефон:
`/usr/bin/curl --silent --show-error "https://smsc.ru/sys/send.php?charset=utf-8&login=msneet&psw=12345678&phones=79196188341&mes=factory.southbridge.ru code: 0000"`

Установка плагина:
```
$ cd /opt/bitnami/apps/redmine/htdocs 
$ bundle install --without development test postgresql sqlite --no-deployment
$ bundle install --without development test postgresql sqlite --deployment
$ ruby bin/rake redmine:plugins RAILS_ENV=production
​$ sudo /opt/bitnami/ctlscript.sh restart
```
Настройки тестового пользователя:
![screenclip](https://cloud.githubusercontent.com/assets/16936262/14586567/b5e7d248-04b5-11e6-9c42-7c86477fd435.png)

После входа тестовым пользователем: пишет "сообщение отправлено", но ничего не приходит
![1](https://cloud.githubusercontent.com/assets/16936262/14586597/36a0033c-04b7-11e6-8951-3a5c46c2b89f.png)

В истории оператора тоже нет отправленных сообщений: [https://smsc.ru/sms/](url)

**Comment by kanfet** [comment]
В конфиге сейчас

```
production:
sms_auth:
    command: '/usr/bin/curl --silent --show-error "https://smsc.ru/sys/send.php?charset=utf-8&login=msneet&psw=12345678&phones=%{phone}&mes=factory.southbridge.ru code: %{password}"'
    password_length: 4
```

А должно быть

```
production:
  sms_auth:
    command: '/usr/bin/curl --silent --show-error "https://smsc.ru/sys/send.php?charset=utf-8&login=msneet&psw=12345678&phones=%{phone}&mes=factory.southbridge.ru code: %{password}"'
    password_length: 4
```
